### PR TITLE
Added Youtube LiveStreaming URLS

### PR DESCRIPTION
**Pull request by robrotheram**
Was testing some YouTube URL's to see if I could replace my current solution with this library and noticed that it did not handle YouTube live streams e.g Lofi hip hop radio https://www.youtube.com/watch?v=5qap5aO4i9A 

So here is a tiny PR that adds the HLS and Dash manifests to the player Streaming Data section

### CODE REVIEW

**Comment by 89z** [comment]
Hello.

`OnesieStreamingUrl` is a very special thing, that only a few people know about.

Is this something that you actually use, or did you add it "just because"?

**Comment by robrotheram** [comment]
OnesieStreamingUrl was the just because. 
I was viewing the JSON API and added the 3 fields that I saw that was missing. 

For my own use-case I only really need the HLS

**Comment by 89z** [comment]
OK I added it:

https://github.com/89z/mech/commit/e6eccda5eb3c665f07014638398fd3e17f08207e

You'll need to use master branch for now, as I am not ready to add a tag at this time.

**Comment by 89z** [comment]
crap, I think I added the wrong one, one second

**Comment by 89z** [comment]
OK I added the HLS here:

https://github.com/89z/mech/commit/96457a963c3cf924ac9c4f51d9f16b9161e9ada4

ignore the commit message

**Comment by 89z** [comment]
arg, one more commit. I didn't like the previous case used. Here is hopefully final commit:

https://github.com/89z/mech/commit/24bd8f83f5fdfffb26520e8f5bf6309778088f4e

**Pull request closed without merging**
